version: 2.1

jobs:
  fail_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1

  after_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "previous failed"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  workflow:
    jobs:
      - fail_job
      - after_fail

